const tailwindConfig = require('../tailwind.config');
const colors = tailwindConfig.theme.extend.colors;
export const CATEGORIES = {
    'transportation': {
        glyph: 'transportation',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['cyan'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: 'bg-hmbEnv-cyan',
        borderCardColor: 'border-hmbEnv-cyan',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'home': {
        glyph: 'boat',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbBlue[500],
        borderColor: colors.hmbSlate[500],
        backgroundColor: 'bg-hmbBlue-500',
        borderCardColor: 'border-hmbBlue-500',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'default': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbBlue[300],
        borderColor: colors.hmbSlate[500],
        backgroundColor: 'bg-hmbBlue-300',
        borderCardColor: 'border-hmbBlue-300',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'food-and-drink': {
        glyph: 'food',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['fucshia'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-fucshia",
        borderCardColor: 'border-hmbEnv-fucshia',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'day-trip-destinations': {
        glyph: 'dayTrip',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['stone'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-stone",
        borderCardColor: 'border-hmbEnv-stone',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'natural-features-and-hikes': {
        glyph: 'nature',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['forest'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-forest",
        borderCardColor: 'border-hmbEnv-forest',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'personal-care': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['mauve'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-mauve",
        borderCardColor: 'border-hmbEnv-mauve',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'professional-services': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['flame'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-flame",
        borderCardColor: 'border-hmbEnv-flame',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'lodging': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['ember'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-ember",
        borderCardColor: 'border-hmbEnv-ember',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'nature-parks-and-recreation': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['grass'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-grass",
        borderCardColor: 'border-hmbEnv-grass',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'provisions': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['torquoise'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-torquoise",
        borderCardColor: 'border-hmbEnv-torquoise',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
    'places-of-worship': {
        glyph: 'defaultIcon',
        glyphColor: colors.hmbBlue[100],
        background: colors.hmbEnv['orange'],
        borderColor: colors.hmbSlate[500],
        backgroundColor: "bg-hmbEnv-orange",
        borderCardColor: 'border-hmbEnv-orange',
        textColor: 'text-hmbBlue-100',
        borderGlyphColor: 'border-hmbBlue-100',
    },
};