export default `    
            anchor
            apiVersion
            name
            clientId
            renderedHtml
            href
            attributes {
              anchor
              backgroundColor
              borderColor
              className
              cssClassName
              fontFamily
              fontSize
              gradient
              linkClassName
              linkTarget
              lock
              placeholder
              rel
              style
              tagName
              textAlign
              textColor
              title
              type
              url
            }`;