name: Deploy to SpinUpWP

on:
  push:
    branches:
      - staging  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WORDPRESS_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_URL }}
      GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
      FAUST_SECRET_KEY: ${{ secrets.FAUST_WP_SECRET_KEY}}
      FAUSTWP_SECRET_KEY: ${{ secrets.FAUST_WP_SECRET_KEY}}
      NEXT_PUBLIC_GOOGLE_MAPS_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_KEY }}
      NEXT_PUBLIC_GOOGLE_MAP_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_ID }}
      SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID : ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET : ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REST_API_APPLICATION_PASSWORD: ${{ secrets.REST_API_APPLICATION_PASSWORD }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: List build directory contents
        run: |
          pwd
          ls -lah ./build
          ls -lah ./public
          
      - name: Adjust permissions for build directory
        run: chmod -R u+rx /home/runner/work/HMB-Next/HMB-Next/build/

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: 18.188.94.119 # Your server's IP address
          username: staging # Your server's username
          key: ${{ secrets.STAGING_SSH }} # Your server's SSH private key
          script: |
            pwd
            ls -lah
            rsync -avz --delete /home/runner/work/HMB-Next/HMB-Next/build/ staging@18.188.94.119:~/files/build/
            pm2 restart all
            rm -rf /var/cache/nginx/*
            rm -rf /cache/staging.hmbmarina.com
