name: Deploy to SpinUpWP STAGING

on:
  push:
    branches:
      - staging  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WORDPRESS_URL: ${{ secrets.NEXT_PUBLIC_WORDPRESS_URL_STAGING }}
      GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
      FAUSTWP_SECRET_KEY: ${{ secrets.FAUST_WP_SECRET_KEY_STAGING }}
      NEXT_PUBLIC_GOOGLE_MAPS_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_KEY }}
      NEXT_PUBLIC_GOOGLE_MAP_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_ID }}
      SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REST_API_APPLICATION_PASSWORD: ${{ secrets.REST_API_APPLICATION_PASSWORD }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and Build Next.js app
        run: |
          npm install
          npm run build

      - name: Rsync All Files Except .env.local
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.env.local'  --exclude='ecosystem.config.js'
          path: ./
          remote_path: ~/files/
          remote_host: 3.15.144.253
          remote_port: 22
          remote_user: staging
          remote_key: ${{ secrets.STAGING_SSH }}

      - name: Restart Application and Clear Cache
        uses: appleboy/ssh-action@master
        with:
          host: 3.15.144.253
          username: staging
          key: ${{ secrets.STAGING_SSH }}
          script: |
            rm -rf /var/cache/nginx/*
            pm2 restart all

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: 3.15.144.253
          username: ${{ secrets.SUDO_USER }}
          key: ${{ secrets.SUDO_SSH }}
          port: 22
          script: |
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S rm -rf /var/cache/nginx/*
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl reload nginx
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
